package in.co.rays.exceptionHandling;

public class TestException {
	public static void main(String[] args) {
		System.out.println("Enter a number: ");
		int a = 5;
		int b = 0;
		int c = a / b;
		System.out.println(c);
		System.out.println("Program complited");
	}
}
